### ISSUE TITLE
local環境構築について 

### ISSUE THREAD

**Issue by Yuichi-Murata01** [TeamRecursion/Hayaoki-Ranking-Frontend#10]
`./node_modules/@material-ui/lab/esm/internal/svg-icons/SuccessOutlined.js
Attempted import error: 'createSvgIcon' is not exported from '@material-ui/core/utils'.`

yarn start
を実施した際に、上記error内容が出てしまうのですが
leandroさんはないですかね？

・問題解決のために行ったこと
①@material-ui/Icore @material-ui/lab　をnpmでinstall
下記サイトの

1. Download dependencies: `npm install @material-ui/lcore @material-ui/lab`　←これを実施後、`yarn start`を実施 
2. Open VSCode to Create File: Snackbar.js with customized snackbar component from the Material-UI Docs.
3. Import File: import CustomizedSnackbars from './Snackbar' in PartnerProfile.js
4. Display Component: <CustomizedSnackbars />

https://github.com/mui-org/material-ui/issues/20482

↓
tailwind cssをinstallしてくれというerrorが表示される

②tailwind cssを再度install
③一番上に記載しているerrorが再度表示される

何かのファイルが足らないんですかね..?
再度developブランチから git fetchしましょうか？

**Comment by mcnLeandro** [comment]
node_modulesはgithubに載せるには容量がデカすぎるので載せていません。
なので
```
yarn install 
```
でたりてないパッケージをインストールできると思います！

**Comment by Yuichi-Murata01** [comment]
> node_modulesはgithubに載せるには容量がデカすぎるので載せていません。
> なので
> 
> ```
> yarn install 
> ```
> 
> でたりてないパッケージをインストールできると思います�！

行けました！
ありがとうございます！！
